apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-monitor
  namespace: ecommerce
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - ecommerce
  selector:
    matchLabels:
      app: backend
  endpoints:
    - port: metrics
      path: /metrics
      scheme: http        
      interval: 15s
