apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: ecommerce
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - name: metrics        
      port: 5000
      targetPort: 5000